welp_mailchimp:
    api_key: to_complete
    lists:
        edadf194f0:
            # provider used in full synchronization
            subscriber_provider: 'yourapp.provider1'
            # webhook secret to secure webhook between MailChimp & your app
            webhook_secret: 'thisIsASecret'
            # The webhook url to be registered to the MailChimp list
            webhook_url: 'https://myapp.com/mailchimp/webhook/endpoint'
        