#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /
    
mailchimp_config:
    resource: "@AppBundle/Controller/MailchimpController.php"
    type:     annotation
    prefix:   /mailchimp

sendinblue_config:
    resource: "@AppBundle/Controller/SendinblueController.php"
    type:     annotation
    prefix:   /mailing
    
mailchimp_webhook:
    resource: "@WelpMailchimpBundle/Resources/config/routing.yml"
    prefix:   /mchook
    
impressum:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /impressum
    
import:
    resource: "@AppBundle/Controller/ImportController.php"
    type:     annotation
    prefix:   /import

cfk_contact:
    path:     /{_locale}/contact
    defaults: { _controller: AppBundle:Cfk:contact }
    
thanks:
    path:     /thanks
    defaults: { _controller: AppBundle:Cfk:thanks }
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"