#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    #resource: "@EasyAdminExtensionBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /
   
sendinblue_config:
    resource: "@AppBundle/Controller/SendinblueController.php"
    type:     annotation
    prefix:   /mailing
   
impressum:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /impressum
    
import:
    resource: "@AppBundle/Controller/ImportController.php"
    type:     annotation
    prefix:   /import

cfk_contact:
    path:     /{_locale}/contact
    defaults: { _controller: AppBundle:Cfk:contact }
    
thanks:
    path:     /{_locale}/thanks
    defaults: { _controller: AppBundle:Cfk:thanks }

subscribe:
    path:     /{_locale}/subscribe
    defaults: { _controller: AppBundle:Cfk:subscribe }
    
confirm:
    path:     /{_locale}/than/confirm
    defaults: { _controller: AppBundle:Cfk:confirm }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"