easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: 'Catégories'
            list:
                title: 'Liste des catégories'
                sort: ['parent', 'ASC']
                actions:
                    #- { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
            show:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - { property: 'parent', label: 'Parent category' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-4', label: 'Caractéristiques', icon: 'pencil' }
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - { property: 'parent', label: 'Parent category' }
