easy_admin:
    #site_name: 'Chemins de Fer du Kaeserberg <small>orchestra</small>'
    site_name: '<img src="http://kaeserberg.ch/Portals/0/Templates/logo-cfk.png" width="180px" height="26px" />'
    
    list:
        max_results: 30
    show:
        max_results: 20
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
        number: '%.2f'
    design:
        brand_color: '#eebb00'
        form_theme:   'vertical'
        templates:
            label_null: '::label_null.html.twig'
        menu:
            - { label: 'Contacts', entity: 'Contact', icon: 'address-book' }
            - { label: 'Entreprises', entity: 'Company', icon: 'building' }
            #- { label: 'menu.about' }
            #- { label: 'menu.about.docs', url: 'https://github.com/laurentmeuwly/rossier_cbsa/tree/master/docs', icon: 'book', target: '_blank' }
            #- { label: 'menu.about.impressum', route: 'impressum', icon: 'info' }
            - { label: 'MailChimp' }
            - { label: 'Informations', route: 'mailchimp', icon: 'info-circle' }
            - { label: 'Configuration' }
            - { label: 'Catégories', entity: 'Category', icon: 'tags'}
            - { label: 'Source', entity: 'Source', icon: 'filter'}
            - { label: 'Paramètres', entity: 'Configuration', icon: 'gear' }
            - { label: 'A propos' }
            - { label: 'Impressum', route: 'impressum', icon: 'info' }
            