easy_admin:
    #site_name: 'Chemins de Fer du Kaeserberg <small>orchestra</small>'
    site_name: '<img src="http://kaeserberg.ch/Portals/0/Templates/logo-cfk.png" width="180px" height="26px" />'
    
    list:
        max_results: 30
    show:
        max_results: 20
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
        number: '%.2f'
    design:
        brand_color: '#eebb00'
        form_theme:   'vertical'
        templates:
            label_null: '::label_null.html.twig'
        menu:
            - { entity: 'Contact', icon: 'address-book' }
            - { entity: 'Company', icon: 'building' }
            - { label: 'Traitement' }
            - { label: app.menu.import, route: 'import', icon: 'download' }
            - { entity: 'ContactNoGenderOrLanguage', icon: 'address-book' }
            - { label: app.menu.mailing }
            - { label: app.menu.information, route: 'sendinblue', icon: 'info-circle' }
            - { label: app.menu.configuration }
            - { entity: 'Category', icon: 'tags'}
            - { entity: 'User', icon: 'user' }
            - { label: app.menu.about }
            - { label: app.menu.impressum, route: 'impressum', icon: 'info' }
            